# Generated by Django 2.2.4 on 2019-08-07 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.CharField(max_length=200)),
                ('mac', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=200)),
                ('ip6', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('firstseen', models.CharField(max_length=200)),
                ('lastseen', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('os', models.CharField(max_length=200)),
                ('recentDeviceName', models.CharField(max_length=200)),
                ('recentDeviceMac', models.CharField(max_length=200)),
                ('recentDeviceSerial', models.CharField(max_length=200)),
                ('ssid', models.CharField(max_length=200)),
                ('vlan', models.CharField(max_length=200)),
                ('switchport', models.CharField(max_length=200)),
                ('usage', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='devices',
            fields=[
                ('lat', models.CharField(max_length=200)),
                ('lng', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('serial', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=200)),
                ('wan1ip', models.CharField(max_length=200)),
                ('wan2ip', models.CharField(max_length=200)),
                ('lanip', models.CharField(max_length=200)),
                ('networkId', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('switchProfileId', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='l3FirewallRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('policy', models.CharField(max_length=200)),
                ('protocol', models.CharField(max_length=200)),
                ('srcport', models.CharField(max_length=200)),
                ('srccidr', models.CharField(max_length=200)),
                ('destport', models.CharField(max_length=200)),
                ('destcidr', models.CharField(max_length=200)),
                ('syslogEnabled', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Licenses',
            fields=[
                ('status', models.CharField(max_length=200)),
                ('expirationDate', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('licensedDeviceCounts', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ssids',
            fields=[
                ('lat', models.CharField(max_length=200)),
                ('lng', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('serial', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=200)),
                ('wan1ip', models.CharField(max_length=200)),
                ('wan2ip', models.CharField(max_length=200)),
                ('lanip', models.CharField(max_length=200)),
                ('networkId', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('switchProfileId', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Vlans',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('networkId', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('applianceIp', models.CharField(max_length=200)),
                ('subnet', models.CharField(max_length=200)),
                ('fixedIpAssignments', models.CharField(max_length=200)),
                ('reservedIpRanges', models.CharField(max_length=200)),
                ('dnsNameservers', models.CharField(max_length=200)),
                ('dhcpHandling', models.CharField(max_length=200)),
                ('dhcpLeaseTime', models.CharField(max_length=200)),
                ('dhcpBootOptionsEnabled', models.CharField(max_length=200)),
                ('dhcpBootNextServer', models.CharField(max_length=200)),
                ('dhcpBootFilename', models.CharField(max_length=200)),
                ('dhcpOptions', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
