# Generated by Django 2.2.4 on 2019-08-08 02:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meraki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerakiInfo',
            fields=[
                ('api_key', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
